/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SCADL & Co (https://sketchfab.com/scadl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tulips-a27208b05e1348bc9c23f761cdc5b724
Title: Tulips
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import tulipScene from "../assets/3d/tulips.glb";

const Tulip = ({ isRotating, setIsRotating, ...props }) => {
    const tulipRef = useRef();
    const { gl, viewport } = useThree();
    const { nodes, materials } = useGLTF(tulipScene);

    const lastX = useRef(0);
    const rotationSpeed = useRef(0.5);
    const dampingFactor = 0.95;

    // eslint-disable-next-line react-hooks/exhaustive-deps
    const handlePointerDown = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(true);

        const clientX = e.touches 
            ?  e.touches[0].clientX 
            : e.clientX;

        lastX.current = clientX;
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
    const handlePointerUp = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(false);
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
    const handlePointerMove = (e) => {
        e.stopPropagation();
        e.preventDefault();

        if (isRotating) {
            const clientX = e.touches 
            ?  e.touches[0].clientX 
            : e.clientX;

            const delta = (clientX - lastX.current) / viewport.width;

            tulipRef.current.rotation.y += delta * 0.01 * Math.PI;

            lastX.current = clientX;

            rotationSpeed.current = delta * 0.01 * Math.PI;
        }
    };

    const handleKeyDown = (e) => {
        if (e.key === 'ArrowLeft') {
            if (!isRotating) setIsRotating(true);
            tulipRef.current.rotation.y += 0.01 * Math.PI;
            rotationSpeed.current = 0.0125;
        } else if (e.key === 'ArrowRight') {
            if (!isRotating) setIsRotating(true);
            tulipRef.current.rotation.y -= 0.01 * Math.PI;
            rotationSpeed.current = -0.0125;
        }
    };

    const handleKeyUp = (e) => {
        if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
            setIsRotating(false);
        }
    };

    useFrame(() => {
        if (!isRotating) {
            rotationSpeed.current *= dampingFactor;

            if (Math.abs(rotationSpeed.current) < 0.001) {
                rotationSpeed.current = 0;
            }

            tulipRef.current.rotation.y += rotationSpeed.current;
        } else {
            const rotation = tulipRef.current.rotation.y;
        }
    });

    useEffect(() => {
        const canvas = gl.domElement;
        canvas.addEventListener('pointerdown', handlePointerDown);
        canvas.addEventListener('pointerup', handlePointerUp);
        canvas.addEventListener('pointermove', handlePointerMove);
        document.addEventListener('keydown', handleKeyDown);
        document.addEventListener('keyup', handleKeyUp);

        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown);
            canvas.removeEventListener('pointerup', handlePointerUp);
            canvas.removeEventListener('pointermove', handlePointerMove);
            document.removeEventListener('keydown', handleKeyDown);
            document.removeEventListener('keyup', handleKeyUp);
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

    return (
        <a.group {...props} ref={tulipRef}>
            <group {...props} dispose={null}>
                <group position={[0, 1.763, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['GrowFX01_Material_#25_0'].geometry}
                    material={materials.Material_25}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['GrowFX01_Material_#25_0_1'].geometry}
                    material={materials.Material_25}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['GrowFX01_Material_#28_0'].geometry}
                    material={materials.Material_28}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['GrowFX01_Material_#26_0'].geometry}
                    material={materials.Material_26}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Line01__0.geometry}
                    material={materials.Line01__0}
                    position={[6.926, 12.393, 0]}
                />
            </group>
        </a.group>
    )
}

export default Tulip